### ISSUE TITLE
Support for lineHeight

### ISSUE THREAD

**Issue by KoltonG** [homebound-team/truss#21]
Enhancement request for line-height function support.

```js
lh(value: Properties["lineHeight"]) { return this.add("lineHeight", value); }
// or
lineHeight(value: Properties["lineHeight"]) { return this.add("lineHeight", value); }
```

**Comment by stephenh** [comment]
Makes sense; I was looking at what Tachyons does:

https://github.com/tachyons-css/tachyons-line-height/blob/master/src/tachyons-line-height.css

```
  .lh-solid { line-height: 1; }
  .lh-title { line-height: 1.25; }
  .lh-copy  { line-height: 1.5; }
```

And tailwinds:

https://tailwindcss.com/docs/line-height

```

leading-3 | line-height: .75rem;
-- | --
leading-4 | line-height: 1rem;
leading-5 | line-height: 1.25rem;
leading-6 | line-height: 1.5rem;
leading-7 | line-height: 1.75rem;
leading-8 | line-height: 2rem;
leading-9 | line-height: 2.25rem;
leading-10 | line-height: 2.5rem;
leading-none | line-height: 1;
leading-tight | line-height: 1.25;
leading-snug | line-height: 1.375;
leading-normal | line-height: 1.5;
leading-relaxed | line-height: 1.625;
leading-loose | line-height: 2;
```

I'm not sure that either of them is perfect-perfect for truss.

Maybe just having a `lh(value)` as you suggested is good enough.

I kinda want to solve line height "for free" by having it built into the font sizes, i.e. like HOP does:

```
const fonts: Record<string, { px: number; lh: number; ls: number }> = {
  f108: { px: 108, lh: 118, ls: -1.6 },
  f96: { px: 96, lh: 105, ls: -1.6 },
  f72: { px: 72, lh: 79, ls: -1.6 },
  f48: { px: 48, lh: 52, ls: -1.6 },
  f32: { px: 32, lh: 35, ls: -1.6 },
  f24: { px: 24, lh: 26, ls: -1.6 },
  f18: { px: 18, lh: 20, ls: -0.8 },
  f16: { px: 16, lh: 18, ls: -0.8 },
  f14: { px: 14, lh: 16, ls: -0.8 },
  f12: { px: 12, lh: 17, ls: -0.8 },
  f10: { px: 10, lh: 12, ls: -0.8 },
};
```

Where picking your font also picks your line height, such that ideally pages never really set line height directly.

That said, could still add `lh` anyway / for now, and doing "font size also sets line height" later.

**Comment by stephenh** [comment]
Added `lh` in #63 and then we've already moved to HOP-style font configs that have `lineHeight` set in each `sm` / `base` / etc., so closing this out.
